services:
  - type: web
    name: moms-moonpie
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - Dockerfile
        - ./
